### PR TITLE
Tidy up config management

### PR DESCRIPTION
**Pull request by calops**
As I talked about before, this defines a new `FromLua` macro in the `strata_derive` crate, and removes `serde`.

There's still work to do to remove some boilerplate but it should be as functional as before.

### CODE REVIEW

**Comment by anantnrg** [comment]
Hey @calops, this is some pretty great stuff! Just one question, previously I had a `libs.rs` file for the `libs` folder and then for different folders inside the `libs` folder, I had different files that pointed to those folders. Now you've changed it so that instead of `libs.rs` there is a `mod.rs` file in the `libs` folder. I just want to know the reason behind it? Does it improve compile times, make it execute faster, make it more cleaner?

PS: I didn't mean to make a new commit. I was experimenting with the `octo.nvim` plugin and instead of making a suggestion, I made the change and created a new commit. Still getting used to NeoVim

**Comment by NyxAlexandra** [comment]
(not him)

`mod.rs` is generally cleaner, as it avoids naming a module twice. It is also easier to rename.

**Comment by anantnrg** [comment]
Oh okay, thx for the info!

**Comment by calops** [comment]
Yep, it's more idiomatic that way and as they said, c easier to rename the module.

**Comment by anantnrg** [comment]
Okay, so can we merge it now? I think it looks pretty great.

**Pull request merged**
