### PR TITLE
rules and bindings are now parsed properly

### PR DESCRIPTION
**Pull request by calops**
As the title says. I think I've tested this thoroughly enough, please tell me if anything's wrong.

There is still work to do on the configuration parsing. Mostly moving away from serde to `FromLua`, but that requires a lot of boilerplate so I'm going to write a proc macro to do this (the one built into mlua isn't working properly).

There's also a bunch of refactoring to do in order to make all the config fields optional. We should probably differentiate the parsed config from the actual global config. The parsed one will be a bunch of structs with every field optional and builders/impls to help parse everything. The global state will only have optional fields where it makes sense, the rest will be defined by the user. And of course we need functions to update the global state from a new config payload.

None of this is hard to do, it's just a bit of code to move around. I'll probably get to it during the next few days.

### CODE REVIEW

**Review by anantnrg — APPROVED** [review]
This looks pretty great! I'll test it out and merge it soon.

**Comment by anantnrg** [comment]
Hey @calops, I came back from school just now and I tested everything and its working as it should be. Should we close the first issue here #3 or just leave it open? I think we can close it and work on any more modifications as features.

**Comment by calops** [comment]
Yeah we can close it and open more specific issues when needed.

**Comment by anantnrg** [comment]
Okay sure!

**Pull request merged**
